name: piBuild
on:
  push:
    branches:
      - '*'
jobs:
  build:
    name: Build
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check branch tag
        run: |
          if [[ ${{ github.ref }} != *"_piBuild"* ]]; then
            exit 0
          fi
      - name: Gradle shadowJar
        env:
          hibp_api_key: ${{ secrets.HIBP_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        run: ./gradlew shadowJar
  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Deploy
        run: |
          file=$(find build/libs -name 'hibp-*-all.jar' -type f)
          pm2 stop hibp
          rm /home/ubuntu/hibp/hibp-0.0.1-all.jar
          cp "$file" /home/ubuntu/hibp/
          pm2 start hibp
